config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:new, :create] #usually only nest to create the child instance
  end
  #shallow nesting, only create nesting routes if you need the id of the parent
  resources :plants, only: [:destroy, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy #if i delete a garden instance, it will delete all the plants attached to it.
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  #@plant.garden
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url, :location)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def new
    #1.Find the specific garden parent instance that we want to attach a plant to
    @garden = Garden.find(params[:garden_id])
    #2.show the form with an empty instance ready to be filled in by the user
    @plant = Plant.new
    # raise
  end

  def create
    # 1.Find the garden parent with the params
    @garden = Garden.find(params[:garden_id])
    # 2. Create a plant instance with strong params
    @plant = Plant.new(plant_params)
    #3. Attach/assign the two instances together. A plant instance belongs to a garden instance
    # @plant.garden_id = @garden.id
    @plant.garden = @garden
    # 3. Save the plant instance
      if @plant.save
        redirect_to garden_path(@garden)
      else
        render :new
      end
  end

  def destroy
    #1.find the plant instance thanks to the parametric url
    plant = Plant.find(params[:id])
    # 2. destroy the plant instance
    plant.destroy
    #3. redirect the user
    redirect_to garden_path(plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
    <%= f.input :location %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>

        <td><%= image_tag garden.banner_url, width: '200px'%></td>
        <td><%= garden.location %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <!-- image_tag @garden.banner_url -->
  <div class="container">
    <h1><%= @garden.name %></h1>
    <%= @garden.location %>
  </div>
</div>


<% @garden.plants.each do |plant|%>
  <%= plant.name %>
  <%= image_tag plant.image_url, width: '100px' %>
  <%#= link_to 'destroy', plant_path(plant), method: :delete, data: {confirm: 'sure????'}  %>
 <%= link_to plant_path(plant), method: :delete, data: {confirm: 'sure????'}  do %>
  <i class="fas fa-trash-alt"></i>
 <% end %>

<% end %>


<%= link_to 'Edit', edit_garden_path(@garden) %> |
<%= link_to 'Back', gardens_path %>

<%= link_to 'add a plant', new_garden_plant_path(@garden) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlantLivecode</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/new.html.erb
<div class="container">
<h1>Add a plant</h1>
<%= simple_form_for([@garden, @plant])  do |f|%>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit :add, class: 'btn btn-primary' %>
<% end %>

</div>